import math
circumference_scalar = 0.64*1.66666666
distance_scalar = 29.240853516

cross_section_length = 19.3 #cm

wheel_diameter = 3.3 #cm
wheel_circumference = 2*math.pi*wheel_diameter*circumference_scalar

kernel_x = [0.06239878019825997, -0.6276032546357554, 1.0553617880647408, 5.2510292791663185, -0.5654825282673032, 1.677137892137101, -3.2311978278927684]
kernel_y = [-0.16531845167217551, -0.42151239124565604, 0.04036665388278525, 0.08433965613119657, 0.053226907017891914, -0.008490659935598253, 0.2421899618716739]